name: Continous Integration

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master,sandbox]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run prettier-check
      - run: npm test -- --coverage
      - name: Deploying code to Productions from master
        run: echo ${{github.ref}}
