name: Test Mail

on:
  push:
    branches: [sandbox]

jobs:
  Send_Mail:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Release
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Latest Release Update
          to: korrapatisaisandeep@hotmail.com
          from: Sai Sandeep
          secure: true
          body: Hi, This is a test Mail
